training:
    batch_size: 128
    batch_size_val: 300
    num_workers: 12
    n_epochs: 200
    early_stop_patience: 20
    gradient_clip: 0.
    validation_interval: 1
    use_eval: False
    seed: 42
    precision: 32
    arcface: True
    max_fpr: 0.1
    mixup: True
    add_noise: False
    center_loss: False  #if use center loss, please add argument 'optimizer_idx' to training_step()
scaler:
    statistic: instance
    normtype: minmax
    dims: [1, 2]
    savepath: ./scaler.ckpt
data:
    audio_folder: "/data/liuyi/data/DCASE_2022_DATA/"
    dev_train_csv: "/data/liuyi/data/DCASE_2022_DATA/metadata/dev_train_data.csv"
    dev_test_csv: "/data/liuyi/data/DCASE_2022_DATA/metadata/dev_test_data.csv"
    eval_train_csv: "/data/liuyi/data/DCASE_2022_DATA/metadata/eval_train_data.csv"
    audio_max_len: 10
opt:
    lr: 0.001
    center_loss_lr: 0.5
feats:
    feature: STFT
    sample_rate: 16000
    n_window: 2048
    hop_length: 512
    f_min: 50
    f_max: 8000
    n_mels: 128
net:
    embedding_size: 128
    num_class: 21
    margin: 0.7
    scale: 30
represent:
    score_type: knn
    pooling_type: knn
    domain_represent: False
